services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    mem_limit: 0.5g
    cpus: '1.0'
    networks:
      - ebsim-net
    restart: always

volumes:
  postgres_data: