x-spark-common:
  &spark-common
  build:
    dockerfile: Dockerfile.spark
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  mem_limit: 4g
  cpus: '2.0'
  networks:
    - ebsim-net
  
services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    env_file:
      - ./env/spark-master.env      

  spark-worker:
    <<: *spark-common
    env_file:
      - ./env/spark-worker.env      
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - spark-master



