x-airflow-common:
  &airflow-common
  build:
    dockerfile: Dockerfile.airflow
  env_file:
    - ./env/airflow.env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ../13-include/jobs:/opt/bitnami/spark/jobs
    - ../13-include/jars:/opt/bitnami/spark/jars
  mem_limit: 2g
  cpus: '2.0'
  networks:
    - ebsim-net

services:
  airflow-webserver:
    <<: *airflow-common
    depends_on:
      - airflow-init
    container_name: airflow-webserver
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://airflow-webserver:8079/health"]
      interval: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      - airflow-webserver
    container_name: airflow-scheduler
    command: scheduler

  airflow-init:
    <<: *airflow-common
    depends_on:
      - postgres
    container_name: airflow-init
    command: bash -c "airflow db init && airflow users create --username $$AIRFLOW_USERNAME \
            --password $$AIRFLOW_PASSWORD --firstname $$AIRFLOW_FIRSTNAME --lastname $$AIRFLOW_LASTNAME \
            --role Admin --email $$AIRFLOW_EMAIL"