services:
  nessie:
    image: ghcr.io/projectnessie/nessie:0.99.0
    container_name: nessie-app 
    env_file:
      - ./env/nessie.env
    mem_limit: 0.5g
    cpus: '1.0'
    networks:
      - ebsim-net
    depends_on:
      - postgres
    restart: always

  
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:25.2
    container_name: dremio-app
    env_file:
      - ./env/dremio.env
    mem_limit: 4g
    cpus: '2.0'
    networks:
      - ebsim-net
    volumes:
      - dremio-data:/opt/dremio/data

volumes:
  nessie-data:
  dremio-data: