services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio-storage
    env_file:
      - ./env/minio.env
    mem_limit: 0.5g
    cpus: '1.0'
    networks:
      - ebsim-net
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

volumes:
  minio_data: