FROM apache/superset:4.1.3

USER root

RUN pip install --upgrade pip

COPY requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

USER superset

ENV SUPERSET_SECRET_KEY=J5ODleCTWBBEb89drjwSiZV11lq1eUlF

RUN superset fab create-admin \
              --username admin \
              --firstname Superset \
              --lastname Admin \
              --email example@mail.xyz \
              --password password

RUN superset db upgrade

RUN superset init