services:
  collector-dis:
    container_name: collector-dis
    env_file:
      - ./env/collector-dis.env
    volumes:
      - ../15-metrics/collector-dis:/app/metrics
    build:
      context: .
      dockerfile: Dockerfile.collector-dis
    networks:
      - ebsim-net
    depends_on:
      - minio